---
title: "R Notebook"
output: html_notebook
---

```{r}
library(DBI)
con <- dbConnect(RPostgres::Postgres(),
                 dbname = 'postgres', 
                 host = 'localhost',
                 port = 5432,
                 user = 'postgres',
                 password = 'password')
```

```{r}
res <- dbSendQuery(con, ("SELECT p.*, ps.*, curr.rating as currrating, prevr.*
FROM PLAYER p
JOIN PLAYER_STATS ps ON p.player_id = ps.player_id
JOIN PLAYER_RATINGS prevr ON p.player_id = prevr.player_id
JOIN PLAYER_RATINGS curr ON p.player_id = curr.player_id
WHERE ps.season = prevr.season AND ps.season = curr.season-1;"))



tab = dbFetch(res)
dbClearResult(res)
```

```{r}
tab
```

```{r}
library(tidyverse)
library(glmnet)
tab$currrating <- as.factor(tab$currrating)
data <- tab
#data <- filter(data, rating > 80)

set.seed(100)
data[is.na(data)] <- 0
train <- data %>% sample_frac(size = 0.7, fac=currrating)
test <- data %>% setdiff(train)
```

```{r}
library(rpart)
library(rpart.plot)
#form <- as.formula(currrating~.)
form <- as.formula(paste("currrating ~ ",paste(filtVars, collapse="+"),sep = ""))

#mod_tree <- rpart(form,data=train)
```

```{r}
library(e1071)
classifier_cl <- naiveBayes(form, data = train)

y_pred <- predict(classifier_cl, newdata = test)
 
# Confusion Matrix
cm <- table(test$currrating, y_pred)
cm
 
# Model Evaluation
confusionMatrix(cm)
```

```{r}
library(randomForest)
mod_rf<- randomForest(form,train,ntree=1000,importance=TRUE)
mod_rf
```

```{r}
library(caret)
p1 <- predict(mod_rf, train)
confusionMatrix(p1, train$currrating)
```

```{r}
p2 <- predict(mod_rf, test)
confusionMatrix(p2, test$currrating)
```

```{r}
# Get variable importance from the model fit
ImpData <- as.data.frame(importance(mod_rf))
ImpData$Var.Names <- row.names(ImpData)

ggplot(ImpData, aes(x=Var.Names, y=`%IncMSE`)) +
  geom_segment( aes(x=Var.Names, xend=Var.Names, y=0, yend=`%IncMSE`), color="skyblue") +
  geom_point(aes(size = IncNodePurity), color="blue", alpha=0.6) +
  theme_light() +
  coord_flip() +
  theme(
    legend.position="bottom",
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  )
```


```{r}
filter(ImpData, IncNodePurity > 50)
filtVars <- filter(ImpData, IncNodePurity > 50)$Var.Names
filtVars <- filtVars[!filtVars == 'card_id']
filtVars
```
